apiVersion: v1
kind: ServiceAccount 
metadata:
  name: rv1111
    #namespace: devops-tools 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: jenkins 
    #namespace: devops-tools
  labels:
    "app.kubernetes.io/name": 'jenkins'
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","list","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-bindings 
    #namespace: devops-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins 
subjects:
- kind: ServiceAccount 
  name: jenkins-admin
    #namespace: devops-tools

